#
# Ch10_ReadingFileProperties_Ex.ipy v.0.1
# The original examples writen in VB.NET and C# can be found in
# Solid Edge Programmer's Guide or in .NET Programmer's Guide
# for Solid Edge (Solid_Edge_API_tcm78-125829.pdf).
#
# Author: Rlee13
# This file is part of IronPython Examples for Solid Edge ST6.
# An up to date version of the software is to be found at:
# https://github.com/Rlee13/
#
# Freeware. For educational purposes only, use it at your own risk.
#
# The program requires Interop.SolidEdge.dll to be copied in its
# folder. The DLL is part of Jason Hewell's project and can be
# downloaded from http://solidedgeinterop.codeplex.com/
# Tested with IronPython 2.7.4 on .NET 4.0 and Solid Edge ST6.
#
# The file has the extension .ipy which is a personal preference,
# feel free to changed it to any other extension.
# Simply run:
#   ipy.exe filename.ipy
#
# History:
# 11.12.13 - Ch10_ReadingFileProperties_Ex.ipy v.0.1
#
import clr
clr.AddReference("Interop.SolidEdge")
clr.AddReference("System.Runtime.InteropServices")

import SolidEdgeDraft as SEDraft
import SolidEdgeFramework as SEFramework
import SolidEdgeConstants as SEConstants
import SolidEdgePart as SEPart
import System.Runtime.InteropServices as SRI
# Console it is not really required as one can use "print"
from System import Console

objProperties = None
objProperty = None
strFormat1 = "[%s]"
strFormat2 = "%s = %s (%s)"

try:
    # Connect to a running instance of Solid Edge
    objApplication = SRI.Marshal.GetActiveObject("SolidEdge.Application")
    # Get a reference to the active document
    objDocument = objApplication.ActiveDocument
    # Get a reference to the document#s property sets collection
    objPropertySets = objDocument.Properties
    # Example: Loop through all properties
    # Note that indexes are one based
    for i in range(objPropertySets.Count):
        objProperties = objPropertySets.Item(i + 1)
        Console.WriteLine(strFormat1 % objProperties.Name)
        # Note that indexes are one based
        for j in range(objProperties.Count):
            objProperty = objProperties.Item(j + 1)
            vt = objProperty.Type
            Console.WriteLine(strFormat2 % (objProperty.Name, objProperty.Value, vt))

        Console.WriteLine()

    # Example: Read property by name
    objProperties = objPropertySets.Item("SummaryInformation")
    objProperty = objProperties.Item("Author")
    print objProperty.Value

except Exception, ex:
    Console.WriteLine(ex)
finally:
    if objProperty is not None:
        SRI.Marshal.ReleaseComObject(objProperty)
        objProperty = None

    if objProperties is not None:
        SRI.Marshal.ReleaseComObject(objProperties)
        objProperties = None

    if objPropertySets is not None:
        SRI.Marshal.ReleaseComObject(objPropertySets)
        objPropertySets = None

    if objDocument is not None:
        SRI.Marshal.ReleaseComObject(objDocument)
        objDocument = None

    if objApplication is not None:
        SRI.Marshal.ReleaseComObject(objApplication)
        objApplication = None

