#
# Ch7_AddingANewOccurrence_Ex.ipy v.0.1
# The original examples writen in VB.NET and C# can be found in
# Solid Edge Programmer's Guide or in .NET Programmer's Guide
# for Solid Edge (Solid_Edge_API_tcm78-125829.pdf)
#
# Author: Rlee13
# This file is part of IronPython Examples for Solid Edge ST6.
# An up to date version of the software is to be found at:
# https://github.com/Rlee13/pyPLY/
#
# Freeware. For educational purposes only, use it on your own risk.
#
# The program requires Interop.SolidEdge.dll to be copied in its
# folder. The DLL is part of Jason Hewell's project and can be
# downloaded from http://solidedgeinterop.codeplex.com/
# Tested with IronPython 2.7.4 on .NET 4.0 and Solid Edge ST6.
#
# The file has the extension .ipy which is a personal preference,
# feel free to changed it to any other extension.
# Simply run:
#   ipy.exe filename.ipy
#
# History:
# 11.12.13 - Ch7_AddingANewOccurrence_Ex.ipy v.0.1
#
import clr
clr.AddReference("Interop.SolidEdge")
clr.AddReference("System.Runtime.InteropServices")

import SolidEdgeDraft as SEDraft
import SolidEdgeFramework as SEFramework
import SolidEdgeConstants as SEConstants
import SolidEdgePart as SEPart
import System.Runtime.InteropServices as SRI
# Console it is not really required as one can use "print"
from System import Console

objApplication = None
objDocuments = None
objAssembly = None
objOccurrences = None
objOccurrence = None

try:
    # Connect to a running instance of Solid Edge
    objApplication = SRI.Marshal.GetActiveObject("SolidEdge.Application")
    # Get a reference to the documents collection
    objDocuments = objApplication.Documents
    # Create a new assembly document
    objAssembly = objDocuments.Add("SolidEdge.AssemblyDocument")
    # Get a reference to the occurrences collection
    objOccurrences = objAssembly.Occurrences
    # Add a part document to the assembly
    objOccurrence = objOccurrences.AddByFilename("C:\Part1.par")
    
except Exception, ex:
    Console.WriteLine(ex)
finally:
    if objOccurrence is not None:
        SRI.Marshal.ReleaseComObject(objOccurrence)
        objOccurrence = None

    if objOccurrences is not None:
        SRI.Marshal.ReleaseComObject(objOccurrences)
        objOccurrences = None
 
    if objAssembly is not None:
        SRI.Marshal.ReleaseComObject(objAssembly)
        objAssembly = None
 
    if objDocuments is not None:
        SRI.Marshal.ReleaseComObject(objDocuments)
        objDocuments = None
 
    if objApplication is not None:
        SRI.Marshal.ReleaseComObject(objApplication)
        objApplication = None
