#
# Ch8_DrawingViews_Ex.ipy v.0.1
# The original examples writen in VB.NET and C# can be found in
# Solid Edge Programmer's Guide or in .NET Programmer's Guide
# for Solid Edge (Solid_Edge_API_tcm78-125829.pdf)
#
# Author: Rlee13
# This file is part of IronPython Examples for Solid Edge ST6.
# An up to date version of the software is to be found at:
# https://github.com/Rlee13/pyPLY/
#
# Freeware. For educational purposes only, use it on your own risk.
#
# The program requires Interop.SolidEdge.dll to be copied in its
# folder. The DLL is part of Jason Hewell's project and can be
# downloaded from http://solidedgeinterop.codeplex.com/
# Tested with IronPython 2.7.4 on .NET 4.0 and Solid Edge ST6.
#
# The file has the extension .ipy which is a personal preference,
# feel free to changed it to any other extension.
# Simply run:
#   ipy.exe filename.ipy
#
# History:
# 11.12.13 - Ch8_DrawingViews_Ex.ipy v.0.1
#
import clr
clr.AddReference("Interop.SolidEdge")
clr.AddReference("System.Runtime.InteropServices")

import SolidEdgeDraft as SEDraft
import SolidEdgeFramework as SEFramework
import SolidEdgeConstants as SEConstants
import System.Runtime.InteropServices as SRI
# It is not really required one can use "print"
from System import Console

objApplication = None
objDocuments = None
objDraft = None
objSheet = None
objModelLinks = None
objModelLink = None
objDrawingViews = None
objDrawingView = None

try:
    # Connect to a running instance of Solid Edge
    objApplication = SRI.Marshal.GetActiveObject("SolidEdge.Application")
    # Get a reference to the documents collection
    objDocuments = objApplication.Documents
    # Add a Draft document
    objDraft = objDocuments.Add("SolidEdge.DraftDocument")
    # Get a reference to the active sheet
    objSheet = objDraft.ActiveSheet
    # Get a reference to the model links collection
    objModelLinks = objDraft.ModelLinks
    # Add a new model link
    objModelLink = objModelLinks.Add("C:\Part1.par")
    # Get a reference to the drawing views collection
    objDrawingViews = objSheet.DrawingViews
    # Add a new drawing view
    objDrawingView = objDrawingViews.AddPartView(
                    objModelLink,
                    SEDraft.ViewOrientationConstants.igFrontView,
                    1,
                    0.1,
                    0.1,
                    SEDraft.PartDrawingViewTypeConstants.sePartDesignedView)
    # Assign a caption
    objDrawingView.CaptionDefinitionTextPrimary = "My New Drawing View"
    # Ensure caption is displayed
    objDrawingView.DisplayCaption = True
except Exception, ex:
    Console.WriteLine(ex)
finally:
    if objDrawingView is not None:
        SRI.Marshal.ReleaseComObject(objDrawingView)
        objDrawingView = None

    if objDrawingViews is not None:
        SRI.Marshal.ReleaseComObject(objDrawingViews)
        objDrawingViews = None

    if objModelLink is not None:
        SRI.Marshal.ReleaseComObject(objModelLink)
        objModelLink = None

    if objModelLinks is not None:
        SRI.Marshal.ReleaseComObject(objModelLinks)
        objModelLinks = None

    if objSheet is not None:
        SRI.Marshal.ReleaseComObject(objSheet)
        objSheet = None

    if objDraft is not None:
        SRI.Marshal.ReleaseComObject(objDraft)
        objDraft = None

    if objDocuments is not None:
        SRI.Marshal.ReleaseComObject(objDocuments)
        objDocuments = None

    if objApplication is not None:
        SRI.Marshal.ReleaseComObject(objApplication)
        objApplication = None